name: CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        type: string
      create_release:
        description: 'Create a GitHub release'
        required: false
        default: false
        type: boolean

jobs:
  build-and-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build JAR
        run: mvn clean package --no-transfer-progress

      - name: Find JAR file
        id: find_jar
        run: echo "jar_file=$(find target -name '*.jar' -not -name '*-sources.jar' -not -name '*-javadoc.jar' | head -1)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: ${{ inputs.create_release }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.tag_name }}
          draft: false
          prerelease: false
          files: ${{ steps.find_jar.outputs.jar_file }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          publish_branch: gh-pages

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          publish_branch: gh-pages
