name: CI

on:
  push:
    branches:
      - main
      - feat/continuous-integration
      - feat/documentation

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build JAR
        run: mvn clean package --no-transfer-progress

      - name: Find JAR file
        id: find_jar
        run: echo "jar_file=$(find target -name '*.jar' -not -name '*-sources.jar' -not -name '*-javadoc.jar' | head -1)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Jar build
          draft: false
          prerelease: false
          files: ${{ steps.find_jar.outputs.jar_file }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          publish_branch: gh-pages
