name: CI

on:
  push:
    branches:
      - main
      - feat/continuous-integration

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build JAR
        run: mvn clean package --no-transfer-progress

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.run_number }}
          release_name: Jar build
          draft: false
          prerelease: false

      - name: Upload JAR to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: scenario-quality-checker.jar
          asset_content_type: application/java-archive

